name: Publish
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '24' 
          registry-url: 'https://registry.npmjs.org'
      - name: Setup
        run: rm -rf node_modules pnpm-lock.yaml package-lock.json .npm/_cacache
          npm ci
      - name: Install
        run: npx pnpm@7.15.0 install 
      - name: Install Dev
        run: npm install --save-dev @types/node
      - name: Build
        run: npx pnpm@7.15.0 build
      - name: Publish
        run: npm publish


