name: Publish
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '24.x' 
          registry-url: 'https://registry.npmjs.org'
      - name: Setup
        run: rm -rf node_modules pnpm-lock.yaml package-lock.json .npm/_cacache
          npm ci
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish


